backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: create {{collection}}/{{slug}}
    update: update {{collection}}/{{slug}}
    delete: delete {{collection}}/{{slug}}
    uploadMedia: upload {{path}}
    deleteMedia: delete {{path}}
    openAuthoring: '{{message}}'

media_folder: "_site/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "note"
    label: "Note"
    folder: 'note'
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: "Layout"
        name: "layout"
        widget: "select"
        default: "layouts/note.njk"
        options:
          - { label: "Global", value: "layouts/global.njk" }
          - { label: "Note", value: "layouts/note.njk" }
        multiple: false
        max: 1
      - label: "Tags"
        name: 'tags'
        widget: 'list'
        default: ['web']
        allow_add: true
        collapsed: false
      - { label: "Modified Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "wiki"
    label: "Wiki"
    folder: 'wiki'
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: "Layout"
        name: "layout"
        widget: "select"
        default: "layouts/wiki.njk"
        options:
          - { label: "Global", value: "layouts/global.njk" }
          - { label: "Wiki", value: "layouts/wiki.njk" }
        multiple: false
        max: 1
      - { label: "Modified Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

site_url: https://notes.shinjith.dev
logo_url: https://shinjith.dev/assets/favicon/android-chrome-512x512.png
